name: PR Checks

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run type check
        run: yarn tsc --noEmit
        env:
          CI: true

      - name: Check for type errors
        if: ${{ failure() }}
        run: echo "::error::Type checking failed. See the error details above."
